# Generated by Django 5.2.16 on 2026-07-23 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('VALID', 'Valid'), ('ASSIGNED', 'Assigned'), ('INVALID', 'Invalid')], default='NEW', max_length=10)),
                ('reservation_number', models.CharField(max_length=50)),
                ('planned_departure_time', models.DateTimeField()),
                ('planned_arrival_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BOARDING_PASS', 'Boarding Pass'), ('ID_CARD', 'ID Card'), ('PASSPORT', 'Passport')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_data', models.BinaryField()),
                ('file_size', models.IntegerField()),
                ('content_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('flight_date', models.DateField()),
                ('airline', models.CharField(max_length=100)),
                ('is_connecting', models.BooleanField(default=False)),
                ('is_problem_flight', models.BooleanField(default=False)),
                ('sequence_order', models.IntegerField(default=0)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='airports.airport')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='cases.case')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='airports.airport')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='GdprConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented', models.BooleanField()),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_consent', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=20)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='cases.case')),
            ],
        ),
    ]
