# Generated by Django 5.2.16 on 2026-07-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_compensation_amount_case_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='airline_mentioned_motive',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('DONT_KNOW', "I don't know")], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='airline_motive',
            field=models.CharField(blank=True, choices=[('TECHNICAL', 'Technical problem'), ('METEOROLOGICAL', 'Meteorological conditions'), ('STRIKE', 'Strike'), ('AIRPORT_PROBLEMS', 'Problems with airport'), ('CREW_PROBLEMS', 'Crew problems'), ('OTHER', 'Other motives')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='cancellation_notice_period',
            field=models.CharField(blank=True, choices=[('MORE_THAN_14_DAYS', 'More than 14 days'), ('LESS_THAN_14_DAYS', 'Less than 14 days'), ('ON_FLIGHT_DAY', 'On flight day')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='delay_arrival',
            field=models.CharField(blank=True, choices=[('LESS_THAN_3H', 'Less than 3 hours'), ('MORE_THAN_3H', 'More than 3 hours'), ('CONNECTION_LOST', 'Connection flight lost')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='denied_boarding_reason',
            field=models.CharField(blank=True, choices=[('OVERBOOKED', 'Flight overbooked'), ('AGGRESSIVE', 'Aggressive behavior with staff'), ('INTOXICATION', 'Intoxication'), ('UNSPECIFIED', 'Unspecified reason')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='denied_boarding_voluntary',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='disruption_type',
            field=models.CharField(blank=True, choices=[('CANCELLATION', 'Cancellation'), ('DELAY', 'Delay'), ('DENIED_BOARDING', 'Denied Boarding')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='incident_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
