# Generated by Django 5.2.16 on 2026-07-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_airline_mentioned_motive_case_airline_motive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='colleague',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
