# Generated by Django 5.2.16 on 2026-07-24 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_colleague'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='airline_mentioned_motive',
        ),
        migrations.RemoveField(
            model_name='case',
            name='airline_motive',
        ),
        migrations.RemoveField(
            model_name='case',
            name='cancellation_notice_period',
        ),
        migrations.RemoveField(
            model_name='case',
            name='colleague',
        ),
        migrations.RemoveField(
            model_name='case',
            name='compensation_amount',
        ),
        migrations.RemoveField(
            model_name='case',
            name='delay_arrival',
        ),
        migrations.RemoveField(
            model_name='case',
            name='denied_boarding_reason',
        ),
        migrations.RemoveField(
            model_name='case',
            name='denied_boarding_voluntary',
        ),
        migrations.RemoveField(
            model_name='case',
            name='disruption_type',
        ),
        migrations.RemoveField(
            model_name='case',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='case',
            name='incident_description',
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
